project:
  type: website

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

website:
  title: "Anshuman Mishra"
  site-url: "https://shivance.github.io/portfolio"
  description: "Personal site of Anshuman Mishra."
  favicon: assets/images/favicon.png
  search: false
  twitter-card:
    creator: "@anshuizme"
    card-style: summary
  open-graph: true
  repo-actions: [edit, issue]
  repo-branch: "master"
  repo-url: "https://github.com/anshuizme/portfolio"
  navbar:
    background: primary
    left:
      - text: "About Me"
        href: pages/about.qmd
      - text: "Authoring"
        href: pages/authoring.qmd
      - text: "Open Source Contributions"
        href: pages/open_source.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Resources"
        href: pages/resources.qmd
    right:
      - icon: twitter
        href: https://twitter.com/anshuizme
      - icon: linkedin
        href: https://www.linkedin.com/in/anshuizme/
      - icon: github
        href: https://github.com/shivance

execute:
  freeze: auto

resources:
  - CNAME